name: Java CI with Maven

# Triggers the workflow on push to 'main', pull requests targeting 'main', and manual dispatch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven and run tests
      run: mvn -B clean test -DsuiteXmlFiles=XMLFiles/membershipSuite.xml --file pom.xml

    # Upload test results
    - name: Upload Surefire Test Results
      if: always()  # Ensure that the reports are uploaded even if the tests fail
      uses: actions/upload-artifact@v3
      with:
        name: surefire-reports
        path: target/surefire-reports/

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
